branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

deploy:
  user: __token__
  true:
    repo: pyupio/safety
    tags: true
    python: "3.6.10"
  distributions: sdist bdist_wheel
  provider: pypi
  password:
    secure: hLWwfIbFbeKGWDU5EZT+89IgVCDc9B8GwLb4YWrfW9bnkfpD3DNjlCXJ1Z2pkxlP+t7YUzNWgSGxxVBQXF1diU5wHMx/qDfQ3zFrWUtZdMu+ffD1sHSs0HoVciCFINse6kgy73WdDtOumrb36/S/QINx+8WuHRACtJmPRvpdfNyA8ttrtTkkEYHqkAAbCl0kSenrcmIsmD38GL99Ow/zZ4KvDmhMG7pShL8pxODEy3YBAEPysh7mNZ9YW6aDcY39Qbfohav/RSCSZpANnrOTcVKz3JPtOeUXzkrrJ2PLDY6UMIfLJGvMMvtHSO5wWK0Fl3kC6QH22Lognb2+iaNjpaIvXc2apl5rzB3dlCRQrvOEE6ZWBmY/zrZaAUeVxWzn45cKmVxQVf4n+lr/06spD6491OMs8jIWT0YXEDdeeZKoxRYK6DbgkQle+FZkFHKx4z0Qveh33gGwo2poU/5kJxiWKtirB/zaTypTkCnX8EWNm2SydpvyJZ+8FbOIUJrKXpuY+1s0pu1zMVibHq/o6/mIIX2ULt5k2crXtyIfy/44duTg3wmtN7q8oCFlBix21caR9eGwz/IFyKJD3iuLYEGzH/sy+cn3HwIyRblX7E05kNCDM0CcUm8JZ5WdE+nsNcSHul4due9DXXHPeKk6rW01kR+af672/xRz5ZnvGZA=

language: python
python:
  - "3.7.7"
install:
  - pip install tox-travis
  - pip install codecov
script:
  - tox
after_success:
  - codecov
